### ISSUE TITLE
Complete Profile Page

### ISSUE THREAD

**Issue by chinmayilondhe** [chinmayilondhe/movieWorld#2]
Add user profile photo. Add text fields for name and country.

**Comment by AndroidLion48** [comment]
Hi, I would like to be assigned to this issue.

**Comment by avezqureshi14** [comment]
Hey @chinmayilondhe can you assign this to me

**Comment by chinmayilondhe** [comment]
Please comment in the issues section. I'll assign the issue to you.

**Comment by Perumallpardhiv** [comment]
@chinmayilondhe
I want to try this, pls assign

**Comment by Perumallpardhiv** [comment]
@chinmayilondhe 
Check #7 which fixes : #2
