### ISSUE TITLE
Search movie by title

### ISSUE THREAD

**Issue by chinmayilondhe** [chinmayilondhe/movieWorld#3]
Search symbol is provided on the homepage. Add functionality to it as follows:
1. User can search the movie based on title.

**Comment by AndroidLion48** [comment]
Hello, may you assign this issue to me.

**Comment by squidrye** [comment]
Hi, I would like to work on this, please assign it to me @chinmayilondhe

**Comment by squidrye** [comment]
added this feature in #8  @chinmayilondhe

**Comment by chinmayilondhe** [comment]
Great  @squidrye
